package com.zhenbang.otw.messagemodel // Or your data package

import com.google.firebase.Timestamp // Use Firestore Timestamp
import com.google.firebase.firestore.ServerTimestamp

data class ChatMessage(
    val messageId: String = "", // Auto-generated by Firestore usually, or set manually if needed
    val senderId: String = "",
    val receiverId: String = "", // Good to have for potential queries/notifications
    val text: String = "",
    @ServerTimestamp // Tells Firestore to set this on the server
    val timestamp: Timestamp? = null // Nullable initially, set by server
) {
    // Add a no-argument constructor for Firestore deserialization if needed,
    // though Kotlin data classes often work directly.
    constructor() : this("", "", "", "", null)
}